### PR TITLE
Feature: Account store validation

### PR DESCRIPTION
**Pull request by typerandom**
Add account store validation to the `EnrichIntegrationFromRemoteConfigStrategy`.

Closes issue #11.

### CODE REVIEW

**Comment by robertjd** [comment]
Code looks good, can we get some tests?

**Comment by robertjd** [comment]
Thanks for the tests!   How would you feel about moving the errors to a properties file?  Like what I've done here:

https://github.com/stormpath/stormpath.js/blob/master/test/spec/client.js#L19

The goal is to prevent duplication of the messages in the codebase.  It also feels one step closer to making it easier to override the message strings, e.g. to support different languages

**Comment by typerandom** [comment]
I'm all for preventing code duplication. The reason why I moved/duplicated some of the error messages was due to code locality. I value that more. I.e. that they made more sense to the tests there than at the top of the file.

But I'm all for moving that into a separate file. Makes a lot more sense and better to manage. So will do that :) :+1:

**Comment by typerandom** [comment]
Got this in a mail from Robert. Adding it here just to keep track of it in the same conversation:

>I'm having one issue (at step 5 below) while verifying it. Can you take a look?  Here is what I'm doing:

>(1) clone the stormpath-node-config repo, change to the feature branch, run npm install, npm link

>(2) in my local clone of express-stormpath, run `npm link stormpath-config` then `npm link`

>(3) in my local clone of this sample project, run `npm link express-stormpath`

>(4) unmap all account stores from my application, start the sample project.  I get the expected error about no account stores, all is good here

>(5) map one account store, but don't set it as the default account store.  rather than the new error about default account store required, I get this:

>[2015-12-16 19:13:36] robert@robert-mbp ~/projects/express-stormpath-sample-project/: node server.js
Initializing Stormpath
/Users/robert/projects/stormpath-node-config/lib/strategy/EnrichIntegrationFromRemoteConfigStrategy.js:165
        callback(err);
        ^
TypeError: undefined is not a function
    at /Users/robert/projects/stormpath-node-config/lib/strategy/EnrichIntegrationFromRemoteConfigStrategy.js:165:9
    at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:67:12)
    at onGetResourceRequestResult (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:278:13)
    at Request.onRequestResult [as _callback] (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:100:14)
    at Request.self.callback (/Users/robert/projects/express-stormpath/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/robert/projects/express-stormpath/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/robert/projects/express-stormpath/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)

**Comment by typerandom** [comment]
@robertjd

Hard-coded strings have now been moved to a separate file.

And I'm unable to replicate the issue as you describe in `"(5) map one account store, but don't set it as the default account store. rather than the new error about default account store required, I get this..."`. For me it works as expected. Are you sure that you don't have any old libraries linked?

**Pull request merged**
